FROM alpine:latest

# Build context is the root of the repo
COPY ../root.txt /root.txt 

RUN echo "This is a dummy Dockerfile for service 2"

CMD ["echo", "Hello world from a dummy container for service 2!"]
